version: "3.9"
services:
  jupyter:
    container_name: jupyter-server
    build: .
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - "./workspace:/home/jovyan/work"
    command: "start.sh jupyter lab --LabApp.token=''"
